all: git-completion.bash mussel-completion.bash

git-completion.bash:
	curl -fsSkL -O https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

mussel-completion.bash:
	curl -fsSkL -O https://raw.githubusercontent.com/axsh/wakame-vdc/feature-mussel-completion/client/mussel/completion/mussel-completion.bash

.PHONY: git-completion.bash mussel-completion.bash
